/*
 * static_model.h
 *
 * automatically generated from config_files/IED0.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_LD1;
extern LogicalNode   iedModel_LD1_LLN0;
extern DataObject    iedModel_LD1_LLN0_Mod;
extern DataAttribute iedModel_LD1_LLN0_Mod_stVal;
extern DataAttribute iedModel_LD1_LLN0_Mod_q;
extern DataAttribute iedModel_LD1_LLN0_Mod_t;
extern DataAttribute iedModel_LD1_LLN0_Mod_ctlModel;
extern DataObject    iedModel_LD1_LLN0_Beh;
extern DataAttribute iedModel_LD1_LLN0_Beh_stVal;
extern DataAttribute iedModel_LD1_LLN0_Beh_q;
extern DataAttribute iedModel_LD1_LLN0_Beh_t;
extern DataObject    iedModel_LD1_LLN0_Health;
extern DataAttribute iedModel_LD1_LLN0_Health_stVal;
extern DataAttribute iedModel_LD1_LLN0_Health_q;
extern DataAttribute iedModel_LD1_LLN0_Health_t;
extern DataObject    iedModel_LD1_LLN0_NamPlt;
extern DataAttribute iedModel_LD1_LLN0_NamPlt_vendor;
extern DataAttribute iedModel_LD1_LLN0_NamPlt_swRev;
extern DataAttribute iedModel_LD1_LLN0_NamPlt_d;
extern DataAttribute iedModel_LD1_LLN0_NamPlt_configRev;
extern DataAttribute iedModel_LD1_LLN0_NamPlt_ldNs;
extern LogicalNode   iedModel_LD1_MMXU1;
extern DataObject    iedModel_LD1_MMXU1_TotW;
extern DataAttribute iedModel_LD1_MMXU1_TotW_mag;
extern DataAttribute iedModel_LD1_MMXU1_TotW_mag_f;
extern DataAttribute iedModel_LD1_MMXU1_TotW_q;
extern DataAttribute iedModel_LD1_MMXU1_TotW_t;
extern DataObject    iedModel_LD1_MMXU1_Beh;
extern DataAttribute iedModel_LD1_MMXU1_Beh_stVal;
extern DataAttribute iedModel_LD1_MMXU1_Beh_q;
extern DataAttribute iedModel_LD1_MMXU1_Beh_t;
extern DataObject    iedModel_LD1_MMXU1_TotVAr;
extern DataAttribute iedModel_LD1_MMXU1_TotVAr_mag;
extern DataAttribute iedModel_LD1_MMXU1_TotVAr_mag_i;
extern DataAttribute iedModel_LD1_MMXU1_TotVAr_q;
extern DataAttribute iedModel_LD1_MMXU1_TotVAr_t;
extern DataObject    iedModel_LD1_MMXU1_TotVA;
extern DataAttribute iedModel_LD1_MMXU1_TotVA_mag;
extern DataAttribute iedModel_LD1_MMXU1_TotVA_mag_i;
extern DataAttribute iedModel_LD1_MMXU1_TotVA_q;
extern DataAttribute iedModel_LD1_MMXU1_TotVA_t;
extern DataObject    iedModel_LD1_MMXU1_PPV;
extern DataObject    iedModel_LD1_MMXU1_PPV_phsAB;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsAB_cVal;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsAB_q;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsAB_t;
extern DataObject    iedModel_LD1_MMXU1_PPV_phsBC;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsBC_cVal;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsBC_q;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsBC_t;
extern DataObject    iedModel_LD1_MMXU1_PPV_phsCA;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsCA_cVal;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsCA_q;
extern DataAttribute iedModel_LD1_MMXU1_PPV_phsCA_t;
extern DataObject    iedModel_LD1_MMXU1_PhV;
extern DataObject    iedModel_LD1_MMXU1_PhV_phsA;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsA_cVal;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsA_q;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsA_t;
extern DataObject    iedModel_LD1_MMXU1_PhV_phsB;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsB_cVal;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsB_q;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsB_t;
extern DataObject    iedModel_LD1_MMXU1_PhV_phsC;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsC_cVal;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsC_q;
extern DataAttribute iedModel_LD1_MMXU1_PhV_phsC_t;
extern DataObject    iedModel_LD1_MMXU1_A;
extern DataObject    iedModel_LD1_MMXU1_A_phsA;
extern DataAttribute iedModel_LD1_MMXU1_A_phsA_cVal;
extern DataAttribute iedModel_LD1_MMXU1_A_phsA_q;
extern DataAttribute iedModel_LD1_MMXU1_A_phsA_t;
extern DataObject    iedModel_LD1_MMXU1_A_phsB;
extern DataAttribute iedModel_LD1_MMXU1_A_phsB_cVal;
extern DataAttribute iedModel_LD1_MMXU1_A_phsB_q;
extern DataAttribute iedModel_LD1_MMXU1_A_phsB_t;
extern DataObject    iedModel_LD1_MMXU1_A_phsC;
extern DataAttribute iedModel_LD1_MMXU1_A_phsC_cVal;
extern DataAttribute iedModel_LD1_MMXU1_A_phsC_q;
extern DataAttribute iedModel_LD1_MMXU1_A_phsC_t;
extern LogicalNode   iedModel_LD1_GGIO1;
extern DataObject    iedModel_LD1_GGIO1_Mod;
extern DataAttribute iedModel_LD1_GGIO1_Mod_stVal;
extern DataAttribute iedModel_LD1_GGIO1_Mod_q;
extern DataAttribute iedModel_LD1_GGIO1_Mod_t;
extern DataAttribute iedModel_LD1_GGIO1_Mod_ctlModel;
extern DataObject    iedModel_LD1_GGIO1_Beh;
extern DataAttribute iedModel_LD1_GGIO1_Beh_stVal;
extern DataAttribute iedModel_LD1_GGIO1_Beh_q;
extern DataAttribute iedModel_LD1_GGIO1_Beh_t;
extern DataObject    iedModel_LD1_GGIO1_Health;
extern DataAttribute iedModel_LD1_GGIO1_Health_stVal;
extern DataAttribute iedModel_LD1_GGIO1_Health_q;
extern DataAttribute iedModel_LD1_GGIO1_Health_t;
extern DataObject    iedModel_LD1_GGIO1_NamPlt;
extern DataAttribute iedModel_LD1_GGIO1_NamPlt_vendor;
extern DataAttribute iedModel_LD1_GGIO1_NamPlt_swRev;
extern DataAttribute iedModel_LD1_GGIO1_NamPlt_d;
extern DataAttribute iedModel_LD1_GGIO1_NamPlt_configRev;
extern DataAttribute iedModel_LD1_GGIO1_NamPlt_ldNs;
extern DataObject    iedModel_LD1_GGIO1_SPC1;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_stVal;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_q;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_ctlVal;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_origin;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_origin_orCat;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_origin_orIdent;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_ctlNum;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_T;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_Test;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_Oper_Check;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_ctlModel;
extern DataAttribute iedModel_LD1_GGIO1_SPC1_t;



#define IEDMODEL_LD1 (&iedModel_LD1)
#define IEDMODEL_LD1_LLN0 (&iedModel_LD1_LLN0)
#define IEDMODEL_LD1_LLN0_Mod (&iedModel_LD1_LLN0_Mod)
#define IEDMODEL_LD1_LLN0_Mod_stVal (&iedModel_LD1_LLN0_Mod_stVal)
#define IEDMODEL_LD1_LLN0_Mod_q (&iedModel_LD1_LLN0_Mod_q)
#define IEDMODEL_LD1_LLN0_Mod_t (&iedModel_LD1_LLN0_Mod_t)
#define IEDMODEL_LD1_LLN0_Mod_ctlModel (&iedModel_LD1_LLN0_Mod_ctlModel)
#define IEDMODEL_LD1_LLN0_Beh (&iedModel_LD1_LLN0_Beh)
#define IEDMODEL_LD1_LLN0_Beh_stVal (&iedModel_LD1_LLN0_Beh_stVal)
#define IEDMODEL_LD1_LLN0_Beh_q (&iedModel_LD1_LLN0_Beh_q)
#define IEDMODEL_LD1_LLN0_Beh_t (&iedModel_LD1_LLN0_Beh_t)
#define IEDMODEL_LD1_LLN0_Health (&iedModel_LD1_LLN0_Health)
#define IEDMODEL_LD1_LLN0_Health_stVal (&iedModel_LD1_LLN0_Health_stVal)
#define IEDMODEL_LD1_LLN0_Health_q (&iedModel_LD1_LLN0_Health_q)
#define IEDMODEL_LD1_LLN0_Health_t (&iedModel_LD1_LLN0_Health_t)
#define IEDMODEL_LD1_LLN0_NamPlt (&iedModel_LD1_LLN0_NamPlt)
#define IEDMODEL_LD1_LLN0_NamPlt_vendor (&iedModel_LD1_LLN0_NamPlt_vendor)
#define IEDMODEL_LD1_LLN0_NamPlt_swRev (&iedModel_LD1_LLN0_NamPlt_swRev)
#define IEDMODEL_LD1_LLN0_NamPlt_d (&iedModel_LD1_LLN0_NamPlt_d)
#define IEDMODEL_LD1_LLN0_NamPlt_configRev (&iedModel_LD1_LLN0_NamPlt_configRev)
#define IEDMODEL_LD1_LLN0_NamPlt_ldNs (&iedModel_LD1_LLN0_NamPlt_ldNs)
#define IEDMODEL_LD1_MMXU1 (&iedModel_LD1_MMXU1)
#define IEDMODEL_LD1_MMXU1_TotW (&iedModel_LD1_MMXU1_TotW)
#define IEDMODEL_LD1_MMXU1_TotW_mag (&iedModel_LD1_MMXU1_TotW_mag)
#define IEDMODEL_LD1_MMXU1_TotW_mag_f (&iedModel_LD1_MMXU1_TotW_mag_f)
#define IEDMODEL_LD1_MMXU1_TotW_q (&iedModel_LD1_MMXU1_TotW_q)
#define IEDMODEL_LD1_MMXU1_TotW_t (&iedModel_LD1_MMXU1_TotW_t)
#define IEDMODEL_LD1_MMXU1_Beh (&iedModel_LD1_MMXU1_Beh)
#define IEDMODEL_LD1_MMXU1_Beh_stVal (&iedModel_LD1_MMXU1_Beh_stVal)
#define IEDMODEL_LD1_MMXU1_Beh_q (&iedModel_LD1_MMXU1_Beh_q)
#define IEDMODEL_LD1_MMXU1_Beh_t (&iedModel_LD1_MMXU1_Beh_t)
#define IEDMODEL_LD1_MMXU1_TotVAr (&iedModel_LD1_MMXU1_TotVAr)
#define IEDMODEL_LD1_MMXU1_TotVAr_mag (&iedModel_LD1_MMXU1_TotVAr_mag)
#define IEDMODEL_LD1_MMXU1_TotVAr_mag_i (&iedModel_LD1_MMXU1_TotVAr_mag_i)
#define IEDMODEL_LD1_MMXU1_TotVAr_q (&iedModel_LD1_MMXU1_TotVAr_q)
#define IEDMODEL_LD1_MMXU1_TotVAr_t (&iedModel_LD1_MMXU1_TotVAr_t)
#define IEDMODEL_LD1_MMXU1_TotVA (&iedModel_LD1_MMXU1_TotVA)
#define IEDMODEL_LD1_MMXU1_TotVA_mag (&iedModel_LD1_MMXU1_TotVA_mag)
#define IEDMODEL_LD1_MMXU1_TotVA_mag_i (&iedModel_LD1_MMXU1_TotVA_mag_i)
#define IEDMODEL_LD1_MMXU1_TotVA_q (&iedModel_LD1_MMXU1_TotVA_q)
#define IEDMODEL_LD1_MMXU1_TotVA_t (&iedModel_LD1_MMXU1_TotVA_t)
#define IEDMODEL_LD1_MMXU1_PPV (&iedModel_LD1_MMXU1_PPV)
#define IEDMODEL_LD1_MMXU1_PPV_phsAB (&iedModel_LD1_MMXU1_PPV_phsAB)
#define IEDMODEL_LD1_MMXU1_PPV_phsAB_cVal (&iedModel_LD1_MMXU1_PPV_phsAB_cVal)
#define IEDMODEL_LD1_MMXU1_PPV_phsAB_q (&iedModel_LD1_MMXU1_PPV_phsAB_q)
#define IEDMODEL_LD1_MMXU1_PPV_phsAB_t (&iedModel_LD1_MMXU1_PPV_phsAB_t)
#define IEDMODEL_LD1_MMXU1_PPV_phsBC (&iedModel_LD1_MMXU1_PPV_phsBC)
#define IEDMODEL_LD1_MMXU1_PPV_phsBC_cVal (&iedModel_LD1_MMXU1_PPV_phsBC_cVal)
#define IEDMODEL_LD1_MMXU1_PPV_phsBC_q (&iedModel_LD1_MMXU1_PPV_phsBC_q)
#define IEDMODEL_LD1_MMXU1_PPV_phsBC_t (&iedModel_LD1_MMXU1_PPV_phsBC_t)
#define IEDMODEL_LD1_MMXU1_PPV_phsCA (&iedModel_LD1_MMXU1_PPV_phsCA)
#define IEDMODEL_LD1_MMXU1_PPV_phsCA_cVal (&iedModel_LD1_MMXU1_PPV_phsCA_cVal)
#define IEDMODEL_LD1_MMXU1_PPV_phsCA_q (&iedModel_LD1_MMXU1_PPV_phsCA_q)
#define IEDMODEL_LD1_MMXU1_PPV_phsCA_t (&iedModel_LD1_MMXU1_PPV_phsCA_t)
#define IEDMODEL_LD1_MMXU1_PhV (&iedModel_LD1_MMXU1_PhV)
#define IEDMODEL_LD1_MMXU1_PhV_phsA (&iedModel_LD1_MMXU1_PhV_phsA)
#define IEDMODEL_LD1_MMXU1_PhV_phsA_cVal (&iedModel_LD1_MMXU1_PhV_phsA_cVal)
#define IEDMODEL_LD1_MMXU1_PhV_phsA_q (&iedModel_LD1_MMXU1_PhV_phsA_q)
#define IEDMODEL_LD1_MMXU1_PhV_phsA_t (&iedModel_LD1_MMXU1_PhV_phsA_t)
#define IEDMODEL_LD1_MMXU1_PhV_phsB (&iedModel_LD1_MMXU1_PhV_phsB)
#define IEDMODEL_LD1_MMXU1_PhV_phsB_cVal (&iedModel_LD1_MMXU1_PhV_phsB_cVal)
#define IEDMODEL_LD1_MMXU1_PhV_phsB_q (&iedModel_LD1_MMXU1_PhV_phsB_q)
#define IEDMODEL_LD1_MMXU1_PhV_phsB_t (&iedModel_LD1_MMXU1_PhV_phsB_t)
#define IEDMODEL_LD1_MMXU1_PhV_phsC (&iedModel_LD1_MMXU1_PhV_phsC)
#define IEDMODEL_LD1_MMXU1_PhV_phsC_cVal (&iedModel_LD1_MMXU1_PhV_phsC_cVal)
#define IEDMODEL_LD1_MMXU1_PhV_phsC_q (&iedModel_LD1_MMXU1_PhV_phsC_q)
#define IEDMODEL_LD1_MMXU1_PhV_phsC_t (&iedModel_LD1_MMXU1_PhV_phsC_t)
#define IEDMODEL_LD1_MMXU1_A (&iedModel_LD1_MMXU1_A)
#define IEDMODEL_LD1_MMXU1_A_phsA (&iedModel_LD1_MMXU1_A_phsA)
#define IEDMODEL_LD1_MMXU1_A_phsA_cVal (&iedModel_LD1_MMXU1_A_phsA_cVal)
#define IEDMODEL_LD1_MMXU1_A_phsA_q (&iedModel_LD1_MMXU1_A_phsA_q)
#define IEDMODEL_LD1_MMXU1_A_phsA_t (&iedModel_LD1_MMXU1_A_phsA_t)
#define IEDMODEL_LD1_MMXU1_A_phsB (&iedModel_LD1_MMXU1_A_phsB)
#define IEDMODEL_LD1_MMXU1_A_phsB_cVal (&iedModel_LD1_MMXU1_A_phsB_cVal)
#define IEDMODEL_LD1_MMXU1_A_phsB_q (&iedModel_LD1_MMXU1_A_phsB_q)
#define IEDMODEL_LD1_MMXU1_A_phsB_t (&iedModel_LD1_MMXU1_A_phsB_t)
#define IEDMODEL_LD1_MMXU1_A_phsC (&iedModel_LD1_MMXU1_A_phsC)
#define IEDMODEL_LD1_MMXU1_A_phsC_cVal (&iedModel_LD1_MMXU1_A_phsC_cVal)
#define IEDMODEL_LD1_MMXU1_A_phsC_q (&iedModel_LD1_MMXU1_A_phsC_q)
#define IEDMODEL_LD1_MMXU1_A_phsC_t (&iedModel_LD1_MMXU1_A_phsC_t)
#define IEDMODEL_LD1_GGIO1 (&iedModel_LD1_GGIO1)
#define IEDMODEL_LD1_GGIO1_Mod (&iedModel_LD1_GGIO1_Mod)
#define IEDMODEL_LD1_GGIO1_Mod_stVal (&iedModel_LD1_GGIO1_Mod_stVal)
#define IEDMODEL_LD1_GGIO1_Mod_q (&iedModel_LD1_GGIO1_Mod_q)
#define IEDMODEL_LD1_GGIO1_Mod_t (&iedModel_LD1_GGIO1_Mod_t)
#define IEDMODEL_LD1_GGIO1_Mod_ctlModel (&iedModel_LD1_GGIO1_Mod_ctlModel)
#define IEDMODEL_LD1_GGIO1_Beh (&iedModel_LD1_GGIO1_Beh)
#define IEDMODEL_LD1_GGIO1_Beh_stVal (&iedModel_LD1_GGIO1_Beh_stVal)
#define IEDMODEL_LD1_GGIO1_Beh_q (&iedModel_LD1_GGIO1_Beh_q)
#define IEDMODEL_LD1_GGIO1_Beh_t (&iedModel_LD1_GGIO1_Beh_t)
#define IEDMODEL_LD1_GGIO1_Health (&iedModel_LD1_GGIO1_Health)
#define IEDMODEL_LD1_GGIO1_Health_stVal (&iedModel_LD1_GGIO1_Health_stVal)
#define IEDMODEL_LD1_GGIO1_Health_q (&iedModel_LD1_GGIO1_Health_q)
#define IEDMODEL_LD1_GGIO1_Health_t (&iedModel_LD1_GGIO1_Health_t)
#define IEDMODEL_LD1_GGIO1_NamPlt (&iedModel_LD1_GGIO1_NamPlt)
#define IEDMODEL_LD1_GGIO1_NamPlt_vendor (&iedModel_LD1_GGIO1_NamPlt_vendor)
#define IEDMODEL_LD1_GGIO1_NamPlt_swRev (&iedModel_LD1_GGIO1_NamPlt_swRev)
#define IEDMODEL_LD1_GGIO1_NamPlt_d (&iedModel_LD1_GGIO1_NamPlt_d)
#define IEDMODEL_LD1_GGIO1_NamPlt_configRev (&iedModel_LD1_GGIO1_NamPlt_configRev)
#define IEDMODEL_LD1_GGIO1_NamPlt_ldNs (&iedModel_LD1_GGIO1_NamPlt_ldNs)
#define IEDMODEL_LD1_GGIO1_SPC1 (&iedModel_LD1_GGIO1_SPC1)
#define IEDMODEL_LD1_GGIO1_SPC1_stVal (&iedModel_LD1_GGIO1_SPC1_stVal)
#define IEDMODEL_LD1_GGIO1_SPC1_q (&iedModel_LD1_GGIO1_SPC1_q)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper (&iedModel_LD1_GGIO1_SPC1_Oper)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_ctlVal (&iedModel_LD1_GGIO1_SPC1_Oper_ctlVal)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_origin (&iedModel_LD1_GGIO1_SPC1_Oper_origin)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_origin_orCat (&iedModel_LD1_GGIO1_SPC1_Oper_origin_orCat)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_origin_orIdent (&iedModel_LD1_GGIO1_SPC1_Oper_origin_orIdent)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_ctlNum (&iedModel_LD1_GGIO1_SPC1_Oper_ctlNum)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_T (&iedModel_LD1_GGIO1_SPC1_Oper_T)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_Test (&iedModel_LD1_GGIO1_SPC1_Oper_Test)
#define IEDMODEL_LD1_GGIO1_SPC1_Oper_Check (&iedModel_LD1_GGIO1_SPC1_Oper_Check)
#define IEDMODEL_LD1_GGIO1_SPC1_ctlModel (&iedModel_LD1_GGIO1_SPC1_ctlModel)
#define IEDMODEL_LD1_GGIO1_SPC1_t (&iedModel_LD1_GGIO1_SPC1_t)

#endif /* STATIC_MODEL_H_ */

