/*
 * static_model.h
 *
 * automatically generated from /home/ubuntu/DEMO/IED/TIED1/config_files/TIED1.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_LD0;
extern LogicalNode   iedModel_LD0_LLN0;
extern DataObject    iedModel_LD0_LLN0_Beh;
extern DataAttribute iedModel_LD0_LLN0_Beh_stVal;
extern DataAttribute iedModel_LD0_LLN0_Beh_q;
extern DataAttribute iedModel_LD0_LLN0_Beh_t;
extern LogicalNode   iedModel_LD0_LPHD1;
extern DataObject    iedModel_LD0_LPHD1_PhyNam;
extern DataAttribute iedModel_LD0_LPHD1_PhyNam_vendor;
extern DataObject    iedModel_LD0_LPHD1_PhyHealth;
extern DataAttribute iedModel_LD0_LPHD1_PhyHealth_stVal;
extern DataAttribute iedModel_LD0_LPHD1_PhyHealth_q;
extern DataAttribute iedModel_LD0_LPHD1_PhyHealth_t;
extern DataObject    iedModel_LD0_LPHD1_Proxy;
extern DataAttribute iedModel_LD0_LPHD1_Proxy_stVal;
extern DataAttribute iedModel_LD0_LPHD1_Proxy_q;
extern DataAttribute iedModel_LD0_LPHD1_Proxy_t;
extern DataObject    iedModel_LD0_LPHD1_PwrUp;
extern DataAttribute iedModel_LD0_LPHD1_PwrUp_stVal;
extern DataAttribute iedModel_LD0_LPHD1_PwrUp_q;
extern DataAttribute iedModel_LD0_LPHD1_PwrUp_t;
extern DataObject    iedModel_LD0_LPHD1_PwrDn;
extern DataAttribute iedModel_LD0_LPHD1_PwrDn_stVal;
extern DataAttribute iedModel_LD0_LPHD1_PwrDn_q;
extern DataAttribute iedModel_LD0_LPHD1_PwrDn_t;
extern DataObject    iedModel_LD0_LPHD1_PwrSupAlm;
extern DataAttribute iedModel_LD0_LPHD1_PwrSupAlm_stVal;
extern DataAttribute iedModel_LD0_LPHD1_PwrSupAlm_q;
extern DataAttribute iedModel_LD0_LPHD1_PwrSupAlm_t;
extern LogicalDevice iedModel_MEAS;
extern LogicalNode   iedModel_MEAS_LLN0;
extern DataObject    iedModel_MEAS_LLN0_Beh;
extern DataAttribute iedModel_MEAS_LLN0_Beh_stVal;
extern DataAttribute iedModel_MEAS_LLN0_Beh_q;
extern DataAttribute iedModel_MEAS_LLN0_Beh_t;
extern LogicalNode   iedModel_MEAS_MMXU1;
extern DataObject    iedModel_MEAS_MMXU1_Beh;
extern DataAttribute iedModel_MEAS_MMXU1_Beh_stVal;
extern DataAttribute iedModel_MEAS_MMXU1_Beh_q;
extern DataAttribute iedModel_MEAS_MMXU1_Beh_t;
extern DataObject    iedModel_MEAS_MMXU1_A;
extern DataObject    iedModel_MEAS_MMXU1_A_phsA;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_q;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_t;
extern DataObject    iedModel_MEAS_MMXU1_A_phsB;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_q;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_t;
extern DataObject    iedModel_MEAS_MMXU1_A_phsC;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_q;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_t;
extern LogicalNode   iedModel_MEAS_MMXU2;
extern DataObject    iedModel_MEAS_MMXU2_Beh;
extern DataAttribute iedModel_MEAS_MMXU2_Beh_stVal;
extern DataAttribute iedModel_MEAS_MMXU2_Beh_q;
extern DataAttribute iedModel_MEAS_MMXU2_Beh_t;
extern DataObject    iedModel_MEAS_MMXU2_A;
extern DataObject    iedModel_MEAS_MMXU2_A_phsA;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsA_cVal;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsA_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsA_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsA_q;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsA_t;
extern DataObject    iedModel_MEAS_MMXU2_A_phsB;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsB_cVal;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsB_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsB_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsB_q;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsB_t;
extern DataObject    iedModel_MEAS_MMXU2_A_phsC;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsC_cVal;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsC_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsC_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsC_q;
extern DataAttribute iedModel_MEAS_MMXU2_A_phsC_t;
extern LogicalDevice iedModel_CTRL;
extern LogicalNode   iedModel_CTRL_LLN0;
extern DataObject    iedModel_CTRL_LLN0_Beh;
extern DataAttribute iedModel_CTRL_LLN0_Beh_stVal;
extern DataAttribute iedModel_CTRL_LLN0_Beh_q;
extern DataAttribute iedModel_CTRL_LLN0_Beh_t;
extern LogicalNode   iedModel_CTRL_CILO1;
extern DataObject    iedModel_CTRL_CILO1_EnaOpn;
extern DataAttribute iedModel_CTRL_CILO1_EnaOpn_stVal;
extern DataAttribute iedModel_CTRL_CILO1_EnaOpn_q;
extern DataAttribute iedModel_CTRL_CILO1_EnaOpn_t;
extern DataObject    iedModel_CTRL_CILO1_NamPlt;
extern DataAttribute iedModel_CTRL_CILO1_NamPlt_vendor;
extern DataAttribute iedModel_CTRL_CILO1_NamPlt_swRev;
extern DataObject    iedModel_CTRL_CILO1_Beh;
extern DataAttribute iedModel_CTRL_CILO1_Beh_stVal;
extern DataAttribute iedModel_CTRL_CILO1_Beh_q;
extern DataAttribute iedModel_CTRL_CILO1_Beh_t;
extern DataObject    iedModel_CTRL_CILO1_EnaCls;
extern DataAttribute iedModel_CTRL_CILO1_EnaCls_stVal;
extern DataAttribute iedModel_CTRL_CILO1_EnaCls_q;
extern DataAttribute iedModel_CTRL_CILO1_EnaCls_t;
extern DataObject    iedModel_CTRL_CILO1_Mod;
extern DataAttribute iedModel_CTRL_CILO1_Mod_stVal;
extern DataAttribute iedModel_CTRL_CILO1_Mod_q;
extern DataAttribute iedModel_CTRL_CILO1_Mod_t;
extern DataAttribute iedModel_CTRL_CILO1_Mod_ctlModel;
extern LogicalNode   iedModel_CTRL_CSWI1;
extern DataObject    iedModel_CTRL_CSWI1_NamPlt;
extern DataAttribute iedModel_CTRL_CSWI1_NamPlt_vendor;
extern DataAttribute iedModel_CTRL_CSWI1_NamPlt_swRev;
extern DataObject    iedModel_CTRL_CSWI1_Beh;
extern DataAttribute iedModel_CTRL_CSWI1_Beh_stVal;
extern DataAttribute iedModel_CTRL_CSWI1_Beh_q;
extern DataAttribute iedModel_CTRL_CSWI1_Beh_t;
extern DataObject    iedModel_CTRL_CSWI1_Loc;
extern DataAttribute iedModel_CTRL_CSWI1_Loc_stVal;
extern DataAttribute iedModel_CTRL_CSWI1_Loc_q;
extern DataAttribute iedModel_CTRL_CSWI1_Loc_t;
extern DataObject    iedModel_CTRL_CSWI1_Health;
extern DataAttribute iedModel_CTRL_CSWI1_Health_stVal;
extern DataAttribute iedModel_CTRL_CSWI1_Health_q;
extern DataAttribute iedModel_CTRL_CSWI1_Health_t;
extern DataObject    iedModel_CTRL_CSWI1_Mod;
extern DataAttribute iedModel_CTRL_CSWI1_Mod_stVal;
extern DataAttribute iedModel_CTRL_CSWI1_Mod_q;
extern DataAttribute iedModel_CTRL_CSWI1_Mod_t;
extern DataAttribute iedModel_CTRL_CSWI1_Mod_ctlModel;
extern DataObject    iedModel_CTRL_CSWI1_Pos;
extern DataAttribute iedModel_CTRL_CSWI1_Pos_stVal;
extern DataAttribute iedModel_CTRL_CSWI1_Pos_q;
extern DataAttribute iedModel_CTRL_CSWI1_Pos_t;
extern DataAttribute iedModel_CTRL_CSWI1_Pos_ctlModel;
extern LogicalNode   iedModel_CTRL_XCBR1;
extern DataObject    iedModel_CTRL_XCBR1_Beh;
extern DataAttribute iedModel_CTRL_XCBR1_Beh_stVal;
extern DataAttribute iedModel_CTRL_XCBR1_Beh_q;
extern DataAttribute iedModel_CTRL_XCBR1_Beh_t;
extern DataObject    iedModel_CTRL_XCBR1_Loc;
extern DataAttribute iedModel_CTRL_XCBR1_Loc_stVal;
extern DataAttribute iedModel_CTRL_XCBR1_Loc_q;
extern DataAttribute iedModel_CTRL_XCBR1_Loc_t;
extern DataObject    iedModel_CTRL_XCBR1_OpCnt;
extern DataAttribute iedModel_CTRL_XCBR1_OpCnt_stVal;
extern DataAttribute iedModel_CTRL_XCBR1_OpCnt_q;
extern DataAttribute iedModel_CTRL_XCBR1_OpCnt_t;
extern DataObject    iedModel_CTRL_XCBR1_Pos;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_stVal;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_q;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_t;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_ctlModel;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_ctlVal;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_origin;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_origin_orCat;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_origin_orIdent;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_ctlNum;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_T;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_Test;
extern DataAttribute iedModel_CTRL_XCBR1_Pos_Oper_Check;
extern DataObject    iedModel_CTRL_XCBR1_BlkOpn;
extern DataAttribute iedModel_CTRL_XCBR1_BlkOpn_ctlModel;
extern DataObject    iedModel_CTRL_XCBR1_BlkCls;
extern DataAttribute iedModel_CTRL_XCBR1_BlkCls_ctlModel;
extern LogicalNode   iedModel_CTRL_GGIO1;
extern DataObject    iedModel_CTRL_GGIO1_Beh;
extern DataAttribute iedModel_CTRL_GGIO1_Beh_stVal;
extern DataAttribute iedModel_CTRL_GGIO1_Beh_q;
extern DataAttribute iedModel_CTRL_GGIO1_Beh_t;
extern DataObject    iedModel_CTRL_GGIO1_SPCSO1;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_ctlModel;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_stVal;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_q;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_t;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_ctlVal;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_origin;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_origin_orCat;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_origin_orIdent;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_ctlNum;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_T;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_Test;
extern DataAttribute iedModel_CTRL_GGIO1_SPCSO1_Oper_Check;
extern LogicalDevice iedModel_PROT;
extern LogicalNode   iedModel_PROT_LLN0;
extern DataObject    iedModel_PROT_LLN0_Beh;
extern DataAttribute iedModel_PROT_LLN0_Beh_stVal;
extern DataAttribute iedModel_PROT_LLN0_Beh_q;
extern DataAttribute iedModel_PROT_LLN0_Beh_t;
extern LogicalNode   iedModel_PROT_PDIF1;
extern DataObject    iedModel_PROT_PDIF1_Str;
extern DataAttribute iedModel_PROT_PDIF1_Str_general;
extern DataAttribute iedModel_PROT_PDIF1_Str_dirGeneral;
extern DataAttribute iedModel_PROT_PDIF1_Str_q;
extern DataAttribute iedModel_PROT_PDIF1_Str_t;
extern DataObject    iedModel_PROT_PDIF1_Beh;
extern DataAttribute iedModel_PROT_PDIF1_Beh_stVal;
extern DataAttribute iedModel_PROT_PDIF1_Beh_q;
extern DataAttribute iedModel_PROT_PDIF1_Beh_t;
extern DataObject    iedModel_PROT_PDIF1_Op;
extern DataAttribute iedModel_PROT_PDIF1_Op_general;
extern DataAttribute iedModel_PROT_PDIF1_Op_q;
extern DataAttribute iedModel_PROT_PDIF1_Op_t;
extern LogicalNode   iedModel_PROT_PTRC1;
extern DataObject    iedModel_PROT_PTRC1_NamPlt;
extern DataAttribute iedModel_PROT_PTRC1_NamPlt_vendor;
extern DataAttribute iedModel_PROT_PTRC1_NamPlt_swRev;
extern DataObject    iedModel_PROT_PTRC1_Tr;
extern DataAttribute iedModel_PROT_PTRC1_Tr_general;
extern DataAttribute iedModel_PROT_PTRC1_Tr_q;
extern DataAttribute iedModel_PROT_PTRC1_Tr_t;
extern DataObject    iedModel_PROT_PTRC1_Beh;
extern DataAttribute iedModel_PROT_PTRC1_Beh_stVal;
extern DataAttribute iedModel_PROT_PTRC1_Beh_q;
extern DataAttribute iedModel_PROT_PTRC1_Beh_t;
extern DataObject    iedModel_PROT_PTRC1_Op;
extern DataAttribute iedModel_PROT_PTRC1_Op_general;
extern DataAttribute iedModel_PROT_PTRC1_Op_q;
extern DataAttribute iedModel_PROT_PTRC1_Op_t;
extern DataObject    iedModel_PROT_PTRC1_Health;
extern DataAttribute iedModel_PROT_PTRC1_Health_stVal;
extern DataAttribute iedModel_PROT_PTRC1_Health_q;
extern DataAttribute iedModel_PROT_PTRC1_Health_t;
extern DataObject    iedModel_PROT_PTRC1_Str;
extern DataAttribute iedModel_PROT_PTRC1_Str_general;
extern DataAttribute iedModel_PROT_PTRC1_Str_dirGeneral;
extern DataAttribute iedModel_PROT_PTRC1_Str_q;
extern DataAttribute iedModel_PROT_PTRC1_Str_t;
extern DataObject    iedModel_PROT_PTRC1_OpCntRs;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_stVal;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_q;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_t;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_ctlModel;
extern DataObject    iedModel_PROT_PTRC1_Mod;
extern DataAttribute iedModel_PROT_PTRC1_Mod_stVal;
extern DataAttribute iedModel_PROT_PTRC1_Mod_q;
extern DataAttribute iedModel_PROT_PTRC1_Mod_t;
extern DataAttribute iedModel_PROT_PTRC1_Mod_ctlModel;



#define IEDMODEL_LD0 (&iedModel_LD0)
#define IEDMODEL_LD0_LLN0 (&iedModel_LD0_LLN0)
#define IEDMODEL_LD0_LLN0_Beh (&iedModel_LD0_LLN0_Beh)
#define IEDMODEL_LD0_LLN0_Beh_stVal (&iedModel_LD0_LLN0_Beh_stVal)
#define IEDMODEL_LD0_LLN0_Beh_q (&iedModel_LD0_LLN0_Beh_q)
#define IEDMODEL_LD0_LLN0_Beh_t (&iedModel_LD0_LLN0_Beh_t)
#define IEDMODEL_LD0_LPHD1 (&iedModel_LD0_LPHD1)
#define IEDMODEL_LD0_LPHD1_PhyNam (&iedModel_LD0_LPHD1_PhyNam)
#define IEDMODEL_LD0_LPHD1_PhyNam_vendor (&iedModel_LD0_LPHD1_PhyNam_vendor)
#define IEDMODEL_LD0_LPHD1_PhyHealth (&iedModel_LD0_LPHD1_PhyHealth)
#define IEDMODEL_LD0_LPHD1_PhyHealth_stVal (&iedModel_LD0_LPHD1_PhyHealth_stVal)
#define IEDMODEL_LD0_LPHD1_PhyHealth_q (&iedModel_LD0_LPHD1_PhyHealth_q)
#define IEDMODEL_LD0_LPHD1_PhyHealth_t (&iedModel_LD0_LPHD1_PhyHealth_t)
#define IEDMODEL_LD0_LPHD1_Proxy (&iedModel_LD0_LPHD1_Proxy)
#define IEDMODEL_LD0_LPHD1_Proxy_stVal (&iedModel_LD0_LPHD1_Proxy_stVal)
#define IEDMODEL_LD0_LPHD1_Proxy_q (&iedModel_LD0_LPHD1_Proxy_q)
#define IEDMODEL_LD0_LPHD1_Proxy_t (&iedModel_LD0_LPHD1_Proxy_t)
#define IEDMODEL_LD0_LPHD1_PwrUp (&iedModel_LD0_LPHD1_PwrUp)
#define IEDMODEL_LD0_LPHD1_PwrUp_stVal (&iedModel_LD0_LPHD1_PwrUp_stVal)
#define IEDMODEL_LD0_LPHD1_PwrUp_q (&iedModel_LD0_LPHD1_PwrUp_q)
#define IEDMODEL_LD0_LPHD1_PwrUp_t (&iedModel_LD0_LPHD1_PwrUp_t)
#define IEDMODEL_LD0_LPHD1_PwrDn (&iedModel_LD0_LPHD1_PwrDn)
#define IEDMODEL_LD0_LPHD1_PwrDn_stVal (&iedModel_LD0_LPHD1_PwrDn_stVal)
#define IEDMODEL_LD0_LPHD1_PwrDn_q (&iedModel_LD0_LPHD1_PwrDn_q)
#define IEDMODEL_LD0_LPHD1_PwrDn_t (&iedModel_LD0_LPHD1_PwrDn_t)
#define IEDMODEL_LD0_LPHD1_PwrSupAlm (&iedModel_LD0_LPHD1_PwrSupAlm)
#define IEDMODEL_LD0_LPHD1_PwrSupAlm_stVal (&iedModel_LD0_LPHD1_PwrSupAlm_stVal)
#define IEDMODEL_LD0_LPHD1_PwrSupAlm_q (&iedModel_LD0_LPHD1_PwrSupAlm_q)
#define IEDMODEL_LD0_LPHD1_PwrSupAlm_t (&iedModel_LD0_LPHD1_PwrSupAlm_t)
#define IEDMODEL_MEAS (&iedModel_MEAS)
#define IEDMODEL_MEAS_LLN0 (&iedModel_MEAS_LLN0)
#define IEDMODEL_MEAS_LLN0_Beh (&iedModel_MEAS_LLN0_Beh)
#define IEDMODEL_MEAS_LLN0_Beh_stVal (&iedModel_MEAS_LLN0_Beh_stVal)
#define IEDMODEL_MEAS_LLN0_Beh_q (&iedModel_MEAS_LLN0_Beh_q)
#define IEDMODEL_MEAS_LLN0_Beh_t (&iedModel_MEAS_LLN0_Beh_t)
#define IEDMODEL_MEAS_MMXU1 (&iedModel_MEAS_MMXU1)
#define IEDMODEL_MEAS_MMXU1_Beh (&iedModel_MEAS_MMXU1_Beh)
#define IEDMODEL_MEAS_MMXU1_Beh_stVal (&iedModel_MEAS_MMXU1_Beh_stVal)
#define IEDMODEL_MEAS_MMXU1_Beh_q (&iedModel_MEAS_MMXU1_Beh_q)
#define IEDMODEL_MEAS_MMXU1_Beh_t (&iedModel_MEAS_MMXU1_Beh_t)
#define IEDMODEL_MEAS_MMXU1_A (&iedModel_MEAS_MMXU1_A)
#define IEDMODEL_MEAS_MMXU1_A_phsA (&iedModel_MEAS_MMXU1_A_phsA)
#define IEDMODEL_MEAS_MMXU1_A_phsA_cVal (&iedModel_MEAS_MMXU1_A_phsA_cVal)
#define IEDMODEL_MEAS_MMXU1_A_phsA_cVal_mag (&iedModel_MEAS_MMXU1_A_phsA_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_A_phsA_cVal_mag_f (&iedModel_MEAS_MMXU1_A_phsA_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_A_phsA_q (&iedModel_MEAS_MMXU1_A_phsA_q)
#define IEDMODEL_MEAS_MMXU1_A_phsA_t (&iedModel_MEAS_MMXU1_A_phsA_t)
#define IEDMODEL_MEAS_MMXU1_A_phsB (&iedModel_MEAS_MMXU1_A_phsB)
#define IEDMODEL_MEAS_MMXU1_A_phsB_cVal (&iedModel_MEAS_MMXU1_A_phsB_cVal)
#define IEDMODEL_MEAS_MMXU1_A_phsB_cVal_mag (&iedModel_MEAS_MMXU1_A_phsB_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_A_phsB_cVal_mag_f (&iedModel_MEAS_MMXU1_A_phsB_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_A_phsB_q (&iedModel_MEAS_MMXU1_A_phsB_q)
#define IEDMODEL_MEAS_MMXU1_A_phsB_t (&iedModel_MEAS_MMXU1_A_phsB_t)
#define IEDMODEL_MEAS_MMXU1_A_phsC (&iedModel_MEAS_MMXU1_A_phsC)
#define IEDMODEL_MEAS_MMXU1_A_phsC_cVal (&iedModel_MEAS_MMXU1_A_phsC_cVal)
#define IEDMODEL_MEAS_MMXU1_A_phsC_cVal_mag (&iedModel_MEAS_MMXU1_A_phsC_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_A_phsC_cVal_mag_f (&iedModel_MEAS_MMXU1_A_phsC_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_A_phsC_q (&iedModel_MEAS_MMXU1_A_phsC_q)
#define IEDMODEL_MEAS_MMXU1_A_phsC_t (&iedModel_MEAS_MMXU1_A_phsC_t)
#define IEDMODEL_MEAS_MMXU2 (&iedModel_MEAS_MMXU2)
#define IEDMODEL_MEAS_MMXU2_Beh (&iedModel_MEAS_MMXU2_Beh)
#define IEDMODEL_MEAS_MMXU2_Beh_stVal (&iedModel_MEAS_MMXU2_Beh_stVal)
#define IEDMODEL_MEAS_MMXU2_Beh_q (&iedModel_MEAS_MMXU2_Beh_q)
#define IEDMODEL_MEAS_MMXU2_Beh_t (&iedModel_MEAS_MMXU2_Beh_t)
#define IEDMODEL_MEAS_MMXU2_A (&iedModel_MEAS_MMXU2_A)
#define IEDMODEL_MEAS_MMXU2_A_phsA (&iedModel_MEAS_MMXU2_A_phsA)
#define IEDMODEL_MEAS_MMXU2_A_phsA_cVal (&iedModel_MEAS_MMXU2_A_phsA_cVal)
#define IEDMODEL_MEAS_MMXU2_A_phsA_cVal_mag (&iedModel_MEAS_MMXU2_A_phsA_cVal_mag)
#define IEDMODEL_MEAS_MMXU2_A_phsA_cVal_mag_f (&iedModel_MEAS_MMXU2_A_phsA_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU2_A_phsA_q (&iedModel_MEAS_MMXU2_A_phsA_q)
#define IEDMODEL_MEAS_MMXU2_A_phsA_t (&iedModel_MEAS_MMXU2_A_phsA_t)
#define IEDMODEL_MEAS_MMXU2_A_phsB (&iedModel_MEAS_MMXU2_A_phsB)
#define IEDMODEL_MEAS_MMXU2_A_phsB_cVal (&iedModel_MEAS_MMXU2_A_phsB_cVal)
#define IEDMODEL_MEAS_MMXU2_A_phsB_cVal_mag (&iedModel_MEAS_MMXU2_A_phsB_cVal_mag)
#define IEDMODEL_MEAS_MMXU2_A_phsB_cVal_mag_f (&iedModel_MEAS_MMXU2_A_phsB_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU2_A_phsB_q (&iedModel_MEAS_MMXU2_A_phsB_q)
#define IEDMODEL_MEAS_MMXU2_A_phsB_t (&iedModel_MEAS_MMXU2_A_phsB_t)
#define IEDMODEL_MEAS_MMXU2_A_phsC (&iedModel_MEAS_MMXU2_A_phsC)
#define IEDMODEL_MEAS_MMXU2_A_phsC_cVal (&iedModel_MEAS_MMXU2_A_phsC_cVal)
#define IEDMODEL_MEAS_MMXU2_A_phsC_cVal_mag (&iedModel_MEAS_MMXU2_A_phsC_cVal_mag)
#define IEDMODEL_MEAS_MMXU2_A_phsC_cVal_mag_f (&iedModel_MEAS_MMXU2_A_phsC_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU2_A_phsC_q (&iedModel_MEAS_MMXU2_A_phsC_q)
#define IEDMODEL_MEAS_MMXU2_A_phsC_t (&iedModel_MEAS_MMXU2_A_phsC_t)
#define IEDMODEL_CTRL (&iedModel_CTRL)
#define IEDMODEL_CTRL_LLN0 (&iedModel_CTRL_LLN0)
#define IEDMODEL_CTRL_LLN0_Beh (&iedModel_CTRL_LLN0_Beh)
#define IEDMODEL_CTRL_LLN0_Beh_stVal (&iedModel_CTRL_LLN0_Beh_stVal)
#define IEDMODEL_CTRL_LLN0_Beh_q (&iedModel_CTRL_LLN0_Beh_q)
#define IEDMODEL_CTRL_LLN0_Beh_t (&iedModel_CTRL_LLN0_Beh_t)
#define IEDMODEL_CTRL_CILO1 (&iedModel_CTRL_CILO1)
#define IEDMODEL_CTRL_CILO1_EnaOpn (&iedModel_CTRL_CILO1_EnaOpn)
#define IEDMODEL_CTRL_CILO1_EnaOpn_stVal (&iedModel_CTRL_CILO1_EnaOpn_stVal)
#define IEDMODEL_CTRL_CILO1_EnaOpn_q (&iedModel_CTRL_CILO1_EnaOpn_q)
#define IEDMODEL_CTRL_CILO1_EnaOpn_t (&iedModel_CTRL_CILO1_EnaOpn_t)
#define IEDMODEL_CTRL_CILO1_NamPlt (&iedModel_CTRL_CILO1_NamPlt)
#define IEDMODEL_CTRL_CILO1_NamPlt_vendor (&iedModel_CTRL_CILO1_NamPlt_vendor)
#define IEDMODEL_CTRL_CILO1_NamPlt_swRev (&iedModel_CTRL_CILO1_NamPlt_swRev)
#define IEDMODEL_CTRL_CILO1_Beh (&iedModel_CTRL_CILO1_Beh)
#define IEDMODEL_CTRL_CILO1_Beh_stVal (&iedModel_CTRL_CILO1_Beh_stVal)
#define IEDMODEL_CTRL_CILO1_Beh_q (&iedModel_CTRL_CILO1_Beh_q)
#define IEDMODEL_CTRL_CILO1_Beh_t (&iedModel_CTRL_CILO1_Beh_t)
#define IEDMODEL_CTRL_CILO1_EnaCls (&iedModel_CTRL_CILO1_EnaCls)
#define IEDMODEL_CTRL_CILO1_EnaCls_stVal (&iedModel_CTRL_CILO1_EnaCls_stVal)
#define IEDMODEL_CTRL_CILO1_EnaCls_q (&iedModel_CTRL_CILO1_EnaCls_q)
#define IEDMODEL_CTRL_CILO1_EnaCls_t (&iedModel_CTRL_CILO1_EnaCls_t)
#define IEDMODEL_CTRL_CILO1_Mod (&iedModel_CTRL_CILO1_Mod)
#define IEDMODEL_CTRL_CILO1_Mod_stVal (&iedModel_CTRL_CILO1_Mod_stVal)
#define IEDMODEL_CTRL_CILO1_Mod_q (&iedModel_CTRL_CILO1_Mod_q)
#define IEDMODEL_CTRL_CILO1_Mod_t (&iedModel_CTRL_CILO1_Mod_t)
#define IEDMODEL_CTRL_CILO1_Mod_ctlModel (&iedModel_CTRL_CILO1_Mod_ctlModel)
#define IEDMODEL_CTRL_CSWI1 (&iedModel_CTRL_CSWI1)
#define IEDMODEL_CTRL_CSWI1_NamPlt (&iedModel_CTRL_CSWI1_NamPlt)
#define IEDMODEL_CTRL_CSWI1_NamPlt_vendor (&iedModel_CTRL_CSWI1_NamPlt_vendor)
#define IEDMODEL_CTRL_CSWI1_NamPlt_swRev (&iedModel_CTRL_CSWI1_NamPlt_swRev)
#define IEDMODEL_CTRL_CSWI1_Beh (&iedModel_CTRL_CSWI1_Beh)
#define IEDMODEL_CTRL_CSWI1_Beh_stVal (&iedModel_CTRL_CSWI1_Beh_stVal)
#define IEDMODEL_CTRL_CSWI1_Beh_q (&iedModel_CTRL_CSWI1_Beh_q)
#define IEDMODEL_CTRL_CSWI1_Beh_t (&iedModel_CTRL_CSWI1_Beh_t)
#define IEDMODEL_CTRL_CSWI1_Loc (&iedModel_CTRL_CSWI1_Loc)
#define IEDMODEL_CTRL_CSWI1_Loc_stVal (&iedModel_CTRL_CSWI1_Loc_stVal)
#define IEDMODEL_CTRL_CSWI1_Loc_q (&iedModel_CTRL_CSWI1_Loc_q)
#define IEDMODEL_CTRL_CSWI1_Loc_t (&iedModel_CTRL_CSWI1_Loc_t)
#define IEDMODEL_CTRL_CSWI1_Health (&iedModel_CTRL_CSWI1_Health)
#define IEDMODEL_CTRL_CSWI1_Health_stVal (&iedModel_CTRL_CSWI1_Health_stVal)
#define IEDMODEL_CTRL_CSWI1_Health_q (&iedModel_CTRL_CSWI1_Health_q)
#define IEDMODEL_CTRL_CSWI1_Health_t (&iedModel_CTRL_CSWI1_Health_t)
#define IEDMODEL_CTRL_CSWI1_Mod (&iedModel_CTRL_CSWI1_Mod)
#define IEDMODEL_CTRL_CSWI1_Mod_stVal (&iedModel_CTRL_CSWI1_Mod_stVal)
#define IEDMODEL_CTRL_CSWI1_Mod_q (&iedModel_CTRL_CSWI1_Mod_q)
#define IEDMODEL_CTRL_CSWI1_Mod_t (&iedModel_CTRL_CSWI1_Mod_t)
#define IEDMODEL_CTRL_CSWI1_Mod_ctlModel (&iedModel_CTRL_CSWI1_Mod_ctlModel)
#define IEDMODEL_CTRL_CSWI1_Pos (&iedModel_CTRL_CSWI1_Pos)
#define IEDMODEL_CTRL_CSWI1_Pos_stVal (&iedModel_CTRL_CSWI1_Pos_stVal)
#define IEDMODEL_CTRL_CSWI1_Pos_q (&iedModel_CTRL_CSWI1_Pos_q)
#define IEDMODEL_CTRL_CSWI1_Pos_t (&iedModel_CTRL_CSWI1_Pos_t)
#define IEDMODEL_CTRL_CSWI1_Pos_ctlModel (&iedModel_CTRL_CSWI1_Pos_ctlModel)
#define IEDMODEL_CTRL_XCBR1 (&iedModel_CTRL_XCBR1)
#define IEDMODEL_CTRL_XCBR1_Beh (&iedModel_CTRL_XCBR1_Beh)
#define IEDMODEL_CTRL_XCBR1_Beh_stVal (&iedModel_CTRL_XCBR1_Beh_stVal)
#define IEDMODEL_CTRL_XCBR1_Beh_q (&iedModel_CTRL_XCBR1_Beh_q)
#define IEDMODEL_CTRL_XCBR1_Beh_t (&iedModel_CTRL_XCBR1_Beh_t)
#define IEDMODEL_CTRL_XCBR1_Loc (&iedModel_CTRL_XCBR1_Loc)
#define IEDMODEL_CTRL_XCBR1_Loc_stVal (&iedModel_CTRL_XCBR1_Loc_stVal)
#define IEDMODEL_CTRL_XCBR1_Loc_q (&iedModel_CTRL_XCBR1_Loc_q)
#define IEDMODEL_CTRL_XCBR1_Loc_t (&iedModel_CTRL_XCBR1_Loc_t)
#define IEDMODEL_CTRL_XCBR1_OpCnt (&iedModel_CTRL_XCBR1_OpCnt)
#define IEDMODEL_CTRL_XCBR1_OpCnt_stVal (&iedModel_CTRL_XCBR1_OpCnt_stVal)
#define IEDMODEL_CTRL_XCBR1_OpCnt_q (&iedModel_CTRL_XCBR1_OpCnt_q)
#define IEDMODEL_CTRL_XCBR1_OpCnt_t (&iedModel_CTRL_XCBR1_OpCnt_t)
#define IEDMODEL_CTRL_XCBR1_Pos (&iedModel_CTRL_XCBR1_Pos)
#define IEDMODEL_CTRL_XCBR1_Pos_stVal (&iedModel_CTRL_XCBR1_Pos_stVal)
#define IEDMODEL_CTRL_XCBR1_Pos_q (&iedModel_CTRL_XCBR1_Pos_q)
#define IEDMODEL_CTRL_XCBR1_Pos_t (&iedModel_CTRL_XCBR1_Pos_t)
#define IEDMODEL_CTRL_XCBR1_Pos_ctlModel (&iedModel_CTRL_XCBR1_Pos_ctlModel)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper (&iedModel_CTRL_XCBR1_Pos_Oper)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_ctlVal (&iedModel_CTRL_XCBR1_Pos_Oper_ctlVal)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_origin (&iedModel_CTRL_XCBR1_Pos_Oper_origin)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_origin_orCat (&iedModel_CTRL_XCBR1_Pos_Oper_origin_orCat)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_origin_orIdent (&iedModel_CTRL_XCBR1_Pos_Oper_origin_orIdent)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_ctlNum (&iedModel_CTRL_XCBR1_Pos_Oper_ctlNum)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_T (&iedModel_CTRL_XCBR1_Pos_Oper_T)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_Test (&iedModel_CTRL_XCBR1_Pos_Oper_Test)
#define IEDMODEL_CTRL_XCBR1_Pos_Oper_Check (&iedModel_CTRL_XCBR1_Pos_Oper_Check)
#define IEDMODEL_CTRL_XCBR1_BlkOpn (&iedModel_CTRL_XCBR1_BlkOpn)
#define IEDMODEL_CTRL_XCBR1_BlkOpn_ctlModel (&iedModel_CTRL_XCBR1_BlkOpn_ctlModel)
#define IEDMODEL_CTRL_XCBR1_BlkCls (&iedModel_CTRL_XCBR1_BlkCls)
#define IEDMODEL_CTRL_XCBR1_BlkCls_ctlModel (&iedModel_CTRL_XCBR1_BlkCls_ctlModel)
#define IEDMODEL_CTRL_GGIO1 (&iedModel_CTRL_GGIO1)
#define IEDMODEL_CTRL_GGIO1_Beh (&iedModel_CTRL_GGIO1_Beh)
#define IEDMODEL_CTRL_GGIO1_Beh_stVal (&iedModel_CTRL_GGIO1_Beh_stVal)
#define IEDMODEL_CTRL_GGIO1_Beh_q (&iedModel_CTRL_GGIO1_Beh_q)
#define IEDMODEL_CTRL_GGIO1_Beh_t (&iedModel_CTRL_GGIO1_Beh_t)
#define IEDMODEL_CTRL_GGIO1_SPCSO1 (&iedModel_CTRL_GGIO1_SPCSO1)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_ctlModel (&iedModel_CTRL_GGIO1_SPCSO1_ctlModel)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_stVal (&iedModel_CTRL_GGIO1_SPCSO1_stVal)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_q (&iedModel_CTRL_GGIO1_SPCSO1_q)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_t (&iedModel_CTRL_GGIO1_SPCSO1_t)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper (&iedModel_CTRL_GGIO1_SPCSO1_Oper)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_ctlVal (&iedModel_CTRL_GGIO1_SPCSO1_Oper_ctlVal)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_origin (&iedModel_CTRL_GGIO1_SPCSO1_Oper_origin)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_origin_orCat (&iedModel_CTRL_GGIO1_SPCSO1_Oper_origin_orCat)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_origin_orIdent (&iedModel_CTRL_GGIO1_SPCSO1_Oper_origin_orIdent)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_ctlNum (&iedModel_CTRL_GGIO1_SPCSO1_Oper_ctlNum)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_T (&iedModel_CTRL_GGIO1_SPCSO1_Oper_T)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_Test (&iedModel_CTRL_GGIO1_SPCSO1_Oper_Test)
#define IEDMODEL_CTRL_GGIO1_SPCSO1_Oper_Check (&iedModel_CTRL_GGIO1_SPCSO1_Oper_Check)
#define IEDMODEL_PROT (&iedModel_PROT)
#define IEDMODEL_PROT_LLN0 (&iedModel_PROT_LLN0)
#define IEDMODEL_PROT_LLN0_Beh (&iedModel_PROT_LLN0_Beh)
#define IEDMODEL_PROT_LLN0_Beh_stVal (&iedModel_PROT_LLN0_Beh_stVal)
#define IEDMODEL_PROT_LLN0_Beh_q (&iedModel_PROT_LLN0_Beh_q)
#define IEDMODEL_PROT_LLN0_Beh_t (&iedModel_PROT_LLN0_Beh_t)
#define IEDMODEL_PROT_PDIF1 (&iedModel_PROT_PDIF1)
#define IEDMODEL_PROT_PDIF1_Str (&iedModel_PROT_PDIF1_Str)
#define IEDMODEL_PROT_PDIF1_Str_general (&iedModel_PROT_PDIF1_Str_general)
#define IEDMODEL_PROT_PDIF1_Str_dirGeneral (&iedModel_PROT_PDIF1_Str_dirGeneral)
#define IEDMODEL_PROT_PDIF1_Str_q (&iedModel_PROT_PDIF1_Str_q)
#define IEDMODEL_PROT_PDIF1_Str_t (&iedModel_PROT_PDIF1_Str_t)
#define IEDMODEL_PROT_PDIF1_Beh (&iedModel_PROT_PDIF1_Beh)
#define IEDMODEL_PROT_PDIF1_Beh_stVal (&iedModel_PROT_PDIF1_Beh_stVal)
#define IEDMODEL_PROT_PDIF1_Beh_q (&iedModel_PROT_PDIF1_Beh_q)
#define IEDMODEL_PROT_PDIF1_Beh_t (&iedModel_PROT_PDIF1_Beh_t)
#define IEDMODEL_PROT_PDIF1_Op (&iedModel_PROT_PDIF1_Op)
#define IEDMODEL_PROT_PDIF1_Op_general (&iedModel_PROT_PDIF1_Op_general)
#define IEDMODEL_PROT_PDIF1_Op_q (&iedModel_PROT_PDIF1_Op_q)
#define IEDMODEL_PROT_PDIF1_Op_t (&iedModel_PROT_PDIF1_Op_t)
#define IEDMODEL_PROT_PTRC1 (&iedModel_PROT_PTRC1)
#define IEDMODEL_PROT_PTRC1_NamPlt (&iedModel_PROT_PTRC1_NamPlt)
#define IEDMODEL_PROT_PTRC1_NamPlt_vendor (&iedModel_PROT_PTRC1_NamPlt_vendor)
#define IEDMODEL_PROT_PTRC1_NamPlt_swRev (&iedModel_PROT_PTRC1_NamPlt_swRev)
#define IEDMODEL_PROT_PTRC1_Tr (&iedModel_PROT_PTRC1_Tr)
#define IEDMODEL_PROT_PTRC1_Tr_general (&iedModel_PROT_PTRC1_Tr_general)
#define IEDMODEL_PROT_PTRC1_Tr_q (&iedModel_PROT_PTRC1_Tr_q)
#define IEDMODEL_PROT_PTRC1_Tr_t (&iedModel_PROT_PTRC1_Tr_t)
#define IEDMODEL_PROT_PTRC1_Beh (&iedModel_PROT_PTRC1_Beh)
#define IEDMODEL_PROT_PTRC1_Beh_stVal (&iedModel_PROT_PTRC1_Beh_stVal)
#define IEDMODEL_PROT_PTRC1_Beh_q (&iedModel_PROT_PTRC1_Beh_q)
#define IEDMODEL_PROT_PTRC1_Beh_t (&iedModel_PROT_PTRC1_Beh_t)
#define IEDMODEL_PROT_PTRC1_Op (&iedModel_PROT_PTRC1_Op)
#define IEDMODEL_PROT_PTRC1_Op_general (&iedModel_PROT_PTRC1_Op_general)
#define IEDMODEL_PROT_PTRC1_Op_q (&iedModel_PROT_PTRC1_Op_q)
#define IEDMODEL_PROT_PTRC1_Op_t (&iedModel_PROT_PTRC1_Op_t)
#define IEDMODEL_PROT_PTRC1_Health (&iedModel_PROT_PTRC1_Health)
#define IEDMODEL_PROT_PTRC1_Health_stVal (&iedModel_PROT_PTRC1_Health_stVal)
#define IEDMODEL_PROT_PTRC1_Health_q (&iedModel_PROT_PTRC1_Health_q)
#define IEDMODEL_PROT_PTRC1_Health_t (&iedModel_PROT_PTRC1_Health_t)
#define IEDMODEL_PROT_PTRC1_Str (&iedModel_PROT_PTRC1_Str)
#define IEDMODEL_PROT_PTRC1_Str_general (&iedModel_PROT_PTRC1_Str_general)
#define IEDMODEL_PROT_PTRC1_Str_dirGeneral (&iedModel_PROT_PTRC1_Str_dirGeneral)
#define IEDMODEL_PROT_PTRC1_Str_q (&iedModel_PROT_PTRC1_Str_q)
#define IEDMODEL_PROT_PTRC1_Str_t (&iedModel_PROT_PTRC1_Str_t)
#define IEDMODEL_PROT_PTRC1_OpCntRs (&iedModel_PROT_PTRC1_OpCntRs)
#define IEDMODEL_PROT_PTRC1_OpCntRs_stVal (&iedModel_PROT_PTRC1_OpCntRs_stVal)
#define IEDMODEL_PROT_PTRC1_OpCntRs_q (&iedModel_PROT_PTRC1_OpCntRs_q)
#define IEDMODEL_PROT_PTRC1_OpCntRs_t (&iedModel_PROT_PTRC1_OpCntRs_t)
#define IEDMODEL_PROT_PTRC1_OpCntRs_ctlModel (&iedModel_PROT_PTRC1_OpCntRs_ctlModel)
#define IEDMODEL_PROT_PTRC1_Mod (&iedModel_PROT_PTRC1_Mod)
#define IEDMODEL_PROT_PTRC1_Mod_stVal (&iedModel_PROT_PTRC1_Mod_stVal)
#define IEDMODEL_PROT_PTRC1_Mod_q (&iedModel_PROT_PTRC1_Mod_q)
#define IEDMODEL_PROT_PTRC1_Mod_t (&iedModel_PROT_PTRC1_Mod_t)
#define IEDMODEL_PROT_PTRC1_Mod_ctlModel (&iedModel_PROT_PTRC1_Mod_ctlModel)

#endif /* STATIC_MODEL_H_ */

