/*
 * static_model.h
 *
 * automatically generated from ied18scl.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_PROT;
extern LogicalNode   iedModel_PROT_LLN0;
extern DataObject    iedModel_PROT_LLN0_Beh;
extern DataAttribute iedModel_PROT_LLN0_Beh_stVal;
extern DataAttribute iedModel_PROT_LLN0_Beh_q;
extern DataAttribute iedModel_PROT_LLN0_Beh_t;
extern LogicalNode   iedModel_PROT_PTRC1;
extern DataObject    iedModel_PROT_PTRC1_NamPlt;
extern DataAttribute iedModel_PROT_PTRC1_NamPlt_vendor;
extern DataAttribute iedModel_PROT_PTRC1_NamPlt_swRev;
extern DataObject    iedModel_PROT_PTRC1_Tr;
extern DataAttribute iedModel_PROT_PTRC1_Tr_general;
extern DataAttribute iedModel_PROT_PTRC1_Tr_q;
extern DataAttribute iedModel_PROT_PTRC1_Tr_t;
extern DataObject    iedModel_PROT_PTRC1_Beh;
extern DataAttribute iedModel_PROT_PTRC1_Beh_stVal;
extern DataAttribute iedModel_PROT_PTRC1_Beh_q;
extern DataAttribute iedModel_PROT_PTRC1_Beh_t;
extern DataObject    iedModel_PROT_PTRC1_Op;
extern DataAttribute iedModel_PROT_PTRC1_Op_general;
extern DataAttribute iedModel_PROT_PTRC1_Op_q;
extern DataAttribute iedModel_PROT_PTRC1_Op_t;
extern DataObject    iedModel_PROT_PTRC1_Health;
extern DataAttribute iedModel_PROT_PTRC1_Health_stVal;
extern DataAttribute iedModel_PROT_PTRC1_Health_q;
extern DataAttribute iedModel_PROT_PTRC1_Health_t;
extern DataObject    iedModel_PROT_PTRC1_Str;
extern DataAttribute iedModel_PROT_PTRC1_Str_general;
extern DataAttribute iedModel_PROT_PTRC1_Str_dirGeneral;
extern DataAttribute iedModel_PROT_PTRC1_Str_q;
extern DataAttribute iedModel_PROT_PTRC1_Str_t;
extern DataObject    iedModel_PROT_PTRC1_OpCntRs;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_stVal;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_q;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_t;
extern DataAttribute iedModel_PROT_PTRC1_OpCntRs_ctlModel;
extern DataObject    iedModel_PROT_PTRC1_Mod;
extern DataAttribute iedModel_PROT_PTRC1_Mod_stVal;
extern DataAttribute iedModel_PROT_PTRC1_Mod_q;
extern DataAttribute iedModel_PROT_PTRC1_Mod_t;
extern DataAttribute iedModel_PROT_PTRC1_Mod_ctlModel;
extern LogicalNode   iedModel_PROT_PTRC2;
extern DataObject    iedModel_PROT_PTRC2_NamPlt;
extern DataAttribute iedModel_PROT_PTRC2_NamPlt_vendor;
extern DataAttribute iedModel_PROT_PTRC2_NamPlt_swRev;
extern DataObject    iedModel_PROT_PTRC2_Tr;
extern DataAttribute iedModel_PROT_PTRC2_Tr_general;
extern DataAttribute iedModel_PROT_PTRC2_Tr_q;
extern DataAttribute iedModel_PROT_PTRC2_Tr_t;
extern DataObject    iedModel_PROT_PTRC2_Beh;
extern DataAttribute iedModel_PROT_PTRC2_Beh_stVal;
extern DataAttribute iedModel_PROT_PTRC2_Beh_q;
extern DataAttribute iedModel_PROT_PTRC2_Beh_t;
extern DataObject    iedModel_PROT_PTRC2_Op;
extern DataAttribute iedModel_PROT_PTRC2_Op_general;
extern DataAttribute iedModel_PROT_PTRC2_Op_q;
extern DataAttribute iedModel_PROT_PTRC2_Op_t;
extern DataObject    iedModel_PROT_PTRC2_Health;
extern DataAttribute iedModel_PROT_PTRC2_Health_stVal;
extern DataAttribute iedModel_PROT_PTRC2_Health_q;
extern DataAttribute iedModel_PROT_PTRC2_Health_t;
extern DataObject    iedModel_PROT_PTRC2_Str;
extern DataAttribute iedModel_PROT_PTRC2_Str_general;
extern DataAttribute iedModel_PROT_PTRC2_Str_dirGeneral;
extern DataAttribute iedModel_PROT_PTRC2_Str_q;
extern DataAttribute iedModel_PROT_PTRC2_Str_t;
extern DataObject    iedModel_PROT_PTRC2_OpCntRs;
extern DataAttribute iedModel_PROT_PTRC2_OpCntRs_stVal;
extern DataAttribute iedModel_PROT_PTRC2_OpCntRs_q;
extern DataAttribute iedModel_PROT_PTRC2_OpCntRs_t;
extern DataAttribute iedModel_PROT_PTRC2_OpCntRs_ctlModel;
extern DataObject    iedModel_PROT_PTRC2_Mod;
extern DataAttribute iedModel_PROT_PTRC2_Mod_stVal;
extern DataAttribute iedModel_PROT_PTRC2_Mod_q;
extern DataAttribute iedModel_PROT_PTRC2_Mod_t;
extern DataAttribute iedModel_PROT_PTRC2_Mod_ctlModel;
extern LogicalNode   iedModel_PROT_PTRC3;
extern DataObject    iedModel_PROT_PTRC3_NamPlt;
extern DataAttribute iedModel_PROT_PTRC3_NamPlt_vendor;
extern DataAttribute iedModel_PROT_PTRC3_NamPlt_swRev;
extern DataObject    iedModel_PROT_PTRC3_Tr;
extern DataAttribute iedModel_PROT_PTRC3_Tr_general;
extern DataAttribute iedModel_PROT_PTRC3_Tr_q;
extern DataAttribute iedModel_PROT_PTRC3_Tr_t;
extern DataObject    iedModel_PROT_PTRC3_Beh;
extern DataAttribute iedModel_PROT_PTRC3_Beh_stVal;
extern DataAttribute iedModel_PROT_PTRC3_Beh_q;
extern DataAttribute iedModel_PROT_PTRC3_Beh_t;
extern DataObject    iedModel_PROT_PTRC3_Op;
extern DataAttribute iedModel_PROT_PTRC3_Op_general;
extern DataAttribute iedModel_PROT_PTRC3_Op_q;
extern DataAttribute iedModel_PROT_PTRC3_Op_t;
extern DataObject    iedModel_PROT_PTRC3_Health;
extern DataAttribute iedModel_PROT_PTRC3_Health_stVal;
extern DataAttribute iedModel_PROT_PTRC3_Health_q;
extern DataAttribute iedModel_PROT_PTRC3_Health_t;
extern DataObject    iedModel_PROT_PTRC3_Str;
extern DataAttribute iedModel_PROT_PTRC3_Str_general;
extern DataAttribute iedModel_PROT_PTRC3_Str_dirGeneral;
extern DataAttribute iedModel_PROT_PTRC3_Str_q;
extern DataAttribute iedModel_PROT_PTRC3_Str_t;
extern DataObject    iedModel_PROT_PTRC3_OpCntRs;
extern DataAttribute iedModel_PROT_PTRC3_OpCntRs_stVal;
extern DataAttribute iedModel_PROT_PTRC3_OpCntRs_q;
extern DataAttribute iedModel_PROT_PTRC3_OpCntRs_t;
extern DataAttribute iedModel_PROT_PTRC3_OpCntRs_ctlModel;
extern DataObject    iedModel_PROT_PTRC3_Mod;
extern DataAttribute iedModel_PROT_PTRC3_Mod_stVal;
extern DataAttribute iedModel_PROT_PTRC3_Mod_q;
extern DataAttribute iedModel_PROT_PTRC3_Mod_t;
extern DataAttribute iedModel_PROT_PTRC3_Mod_ctlModel;
extern LogicalNode   iedModel_PROT_PTRC4;
extern DataObject    iedModel_PROT_PTRC4_NamPlt;
extern DataAttribute iedModel_PROT_PTRC4_NamPlt_vendor;
extern DataAttribute iedModel_PROT_PTRC4_NamPlt_swRev;
extern DataObject    iedModel_PROT_PTRC4_Tr;
extern DataAttribute iedModel_PROT_PTRC4_Tr_general;
extern DataAttribute iedModel_PROT_PTRC4_Tr_q;
extern DataAttribute iedModel_PROT_PTRC4_Tr_t;
extern DataObject    iedModel_PROT_PTRC4_Beh;
extern DataAttribute iedModel_PROT_PTRC4_Beh_stVal;
extern DataAttribute iedModel_PROT_PTRC4_Beh_q;
extern DataAttribute iedModel_PROT_PTRC4_Beh_t;
extern DataObject    iedModel_PROT_PTRC4_Op;
extern DataAttribute iedModel_PROT_PTRC4_Op_general;
extern DataAttribute iedModel_PROT_PTRC4_Op_q;
extern DataAttribute iedModel_PROT_PTRC4_Op_t;
extern DataObject    iedModel_PROT_PTRC4_Health;
extern DataAttribute iedModel_PROT_PTRC4_Health_stVal;
extern DataAttribute iedModel_PROT_PTRC4_Health_q;
extern DataAttribute iedModel_PROT_PTRC4_Health_t;
extern DataObject    iedModel_PROT_PTRC4_Str;
extern DataAttribute iedModel_PROT_PTRC4_Str_general;
extern DataAttribute iedModel_PROT_PTRC4_Str_dirGeneral;
extern DataAttribute iedModel_PROT_PTRC4_Str_q;
extern DataAttribute iedModel_PROT_PTRC4_Str_t;
extern DataObject    iedModel_PROT_PTRC4_OpCntRs;
extern DataAttribute iedModel_PROT_PTRC4_OpCntRs_stVal;
extern DataAttribute iedModel_PROT_PTRC4_OpCntRs_q;
extern DataAttribute iedModel_PROT_PTRC4_OpCntRs_t;
extern DataAttribute iedModel_PROT_PTRC4_OpCntRs_ctlModel;
extern DataObject    iedModel_PROT_PTRC4_Mod;
extern DataAttribute iedModel_PROT_PTRC4_Mod_stVal;
extern DataAttribute iedModel_PROT_PTRC4_Mod_q;
extern DataAttribute iedModel_PROT_PTRC4_Mod_t;
extern DataAttribute iedModel_PROT_PTRC4_Mod_ctlModel;



#define IEDMODEL_PROT (&iedModel_PROT)
#define IEDMODEL_PROT_LLN0 (&iedModel_PROT_LLN0)
#define IEDMODEL_PROT_LLN0_Beh (&iedModel_PROT_LLN0_Beh)
#define IEDMODEL_PROT_LLN0_Beh_stVal (&iedModel_PROT_LLN0_Beh_stVal)
#define IEDMODEL_PROT_LLN0_Beh_q (&iedModel_PROT_LLN0_Beh_q)
#define IEDMODEL_PROT_LLN0_Beh_t (&iedModel_PROT_LLN0_Beh_t)
#define IEDMODEL_PROT_PTRC1 (&iedModel_PROT_PTRC1)
#define IEDMODEL_PROT_PTRC1_NamPlt (&iedModel_PROT_PTRC1_NamPlt)
#define IEDMODEL_PROT_PTRC1_NamPlt_vendor (&iedModel_PROT_PTRC1_NamPlt_vendor)
#define IEDMODEL_PROT_PTRC1_NamPlt_swRev (&iedModel_PROT_PTRC1_NamPlt_swRev)
#define IEDMODEL_PROT_PTRC1_Tr (&iedModel_PROT_PTRC1_Tr)
#define IEDMODEL_PROT_PTRC1_Tr_general (&iedModel_PROT_PTRC1_Tr_general)
#define IEDMODEL_PROT_PTRC1_Tr_q (&iedModel_PROT_PTRC1_Tr_q)
#define IEDMODEL_PROT_PTRC1_Tr_t (&iedModel_PROT_PTRC1_Tr_t)
#define IEDMODEL_PROT_PTRC1_Beh (&iedModel_PROT_PTRC1_Beh)
#define IEDMODEL_PROT_PTRC1_Beh_stVal (&iedModel_PROT_PTRC1_Beh_stVal)
#define IEDMODEL_PROT_PTRC1_Beh_q (&iedModel_PROT_PTRC1_Beh_q)
#define IEDMODEL_PROT_PTRC1_Beh_t (&iedModel_PROT_PTRC1_Beh_t)
#define IEDMODEL_PROT_PTRC1_Op (&iedModel_PROT_PTRC1_Op)
#define IEDMODEL_PROT_PTRC1_Op_general (&iedModel_PROT_PTRC1_Op_general)
#define IEDMODEL_PROT_PTRC1_Op_q (&iedModel_PROT_PTRC1_Op_q)
#define IEDMODEL_PROT_PTRC1_Op_t (&iedModel_PROT_PTRC1_Op_t)
#define IEDMODEL_PROT_PTRC1_Health (&iedModel_PROT_PTRC1_Health)
#define IEDMODEL_PROT_PTRC1_Health_stVal (&iedModel_PROT_PTRC1_Health_stVal)
#define IEDMODEL_PROT_PTRC1_Health_q (&iedModel_PROT_PTRC1_Health_q)
#define IEDMODEL_PROT_PTRC1_Health_t (&iedModel_PROT_PTRC1_Health_t)
#define IEDMODEL_PROT_PTRC1_Str (&iedModel_PROT_PTRC1_Str)
#define IEDMODEL_PROT_PTRC1_Str_general (&iedModel_PROT_PTRC1_Str_general)
#define IEDMODEL_PROT_PTRC1_Str_dirGeneral (&iedModel_PROT_PTRC1_Str_dirGeneral)
#define IEDMODEL_PROT_PTRC1_Str_q (&iedModel_PROT_PTRC1_Str_q)
#define IEDMODEL_PROT_PTRC1_Str_t (&iedModel_PROT_PTRC1_Str_t)
#define IEDMODEL_PROT_PTRC1_OpCntRs (&iedModel_PROT_PTRC1_OpCntRs)
#define IEDMODEL_PROT_PTRC1_OpCntRs_stVal (&iedModel_PROT_PTRC1_OpCntRs_stVal)
#define IEDMODEL_PROT_PTRC1_OpCntRs_q (&iedModel_PROT_PTRC1_OpCntRs_q)
#define IEDMODEL_PROT_PTRC1_OpCntRs_t (&iedModel_PROT_PTRC1_OpCntRs_t)
#define IEDMODEL_PROT_PTRC1_OpCntRs_ctlModel (&iedModel_PROT_PTRC1_OpCntRs_ctlModel)
#define IEDMODEL_PROT_PTRC1_Mod (&iedModel_PROT_PTRC1_Mod)
#define IEDMODEL_PROT_PTRC1_Mod_stVal (&iedModel_PROT_PTRC1_Mod_stVal)
#define IEDMODEL_PROT_PTRC1_Mod_q (&iedModel_PROT_PTRC1_Mod_q)
#define IEDMODEL_PROT_PTRC1_Mod_t (&iedModel_PROT_PTRC1_Mod_t)
#define IEDMODEL_PROT_PTRC1_Mod_ctlModel (&iedModel_PROT_PTRC1_Mod_ctlModel)
#define IEDMODEL_PROT_PTRC2 (&iedModel_PROT_PTRC2)
#define IEDMODEL_PROT_PTRC2_NamPlt (&iedModel_PROT_PTRC2_NamPlt)
#define IEDMODEL_PROT_PTRC2_NamPlt_vendor (&iedModel_PROT_PTRC2_NamPlt_vendor)
#define IEDMODEL_PROT_PTRC2_NamPlt_swRev (&iedModel_PROT_PTRC2_NamPlt_swRev)
#define IEDMODEL_PROT_PTRC2_Tr (&iedModel_PROT_PTRC2_Tr)
#define IEDMODEL_PROT_PTRC2_Tr_general (&iedModel_PROT_PTRC2_Tr_general)
#define IEDMODEL_PROT_PTRC2_Tr_q (&iedModel_PROT_PTRC2_Tr_q)
#define IEDMODEL_PROT_PTRC2_Tr_t (&iedModel_PROT_PTRC2_Tr_t)
#define IEDMODEL_PROT_PTRC2_Beh (&iedModel_PROT_PTRC2_Beh)
#define IEDMODEL_PROT_PTRC2_Beh_stVal (&iedModel_PROT_PTRC2_Beh_stVal)
#define IEDMODEL_PROT_PTRC2_Beh_q (&iedModel_PROT_PTRC2_Beh_q)
#define IEDMODEL_PROT_PTRC2_Beh_t (&iedModel_PROT_PTRC2_Beh_t)
#define IEDMODEL_PROT_PTRC2_Op (&iedModel_PROT_PTRC2_Op)
#define IEDMODEL_PROT_PTRC2_Op_general (&iedModel_PROT_PTRC2_Op_general)
#define IEDMODEL_PROT_PTRC2_Op_q (&iedModel_PROT_PTRC2_Op_q)
#define IEDMODEL_PROT_PTRC2_Op_t (&iedModel_PROT_PTRC2_Op_t)
#define IEDMODEL_PROT_PTRC2_Health (&iedModel_PROT_PTRC2_Health)
#define IEDMODEL_PROT_PTRC2_Health_stVal (&iedModel_PROT_PTRC2_Health_stVal)
#define IEDMODEL_PROT_PTRC2_Health_q (&iedModel_PROT_PTRC2_Health_q)
#define IEDMODEL_PROT_PTRC2_Health_t (&iedModel_PROT_PTRC2_Health_t)
#define IEDMODEL_PROT_PTRC2_Str (&iedModel_PROT_PTRC2_Str)
#define IEDMODEL_PROT_PTRC2_Str_general (&iedModel_PROT_PTRC2_Str_general)
#define IEDMODEL_PROT_PTRC2_Str_dirGeneral (&iedModel_PROT_PTRC2_Str_dirGeneral)
#define IEDMODEL_PROT_PTRC2_Str_q (&iedModel_PROT_PTRC2_Str_q)
#define IEDMODEL_PROT_PTRC2_Str_t (&iedModel_PROT_PTRC2_Str_t)
#define IEDMODEL_PROT_PTRC2_OpCntRs (&iedModel_PROT_PTRC2_OpCntRs)
#define IEDMODEL_PROT_PTRC2_OpCntRs_stVal (&iedModel_PROT_PTRC2_OpCntRs_stVal)
#define IEDMODEL_PROT_PTRC2_OpCntRs_q (&iedModel_PROT_PTRC2_OpCntRs_q)
#define IEDMODEL_PROT_PTRC2_OpCntRs_t (&iedModel_PROT_PTRC2_OpCntRs_t)
#define IEDMODEL_PROT_PTRC2_OpCntRs_ctlModel (&iedModel_PROT_PTRC2_OpCntRs_ctlModel)
#define IEDMODEL_PROT_PTRC2_Mod (&iedModel_PROT_PTRC2_Mod)
#define IEDMODEL_PROT_PTRC2_Mod_stVal (&iedModel_PROT_PTRC2_Mod_stVal)
#define IEDMODEL_PROT_PTRC2_Mod_q (&iedModel_PROT_PTRC2_Mod_q)
#define IEDMODEL_PROT_PTRC2_Mod_t (&iedModel_PROT_PTRC2_Mod_t)
#define IEDMODEL_PROT_PTRC2_Mod_ctlModel (&iedModel_PROT_PTRC2_Mod_ctlModel)
#define IEDMODEL_PROT_PTRC3 (&iedModel_PROT_PTRC3)
#define IEDMODEL_PROT_PTRC3_NamPlt (&iedModel_PROT_PTRC3_NamPlt)
#define IEDMODEL_PROT_PTRC3_NamPlt_vendor (&iedModel_PROT_PTRC3_NamPlt_vendor)
#define IEDMODEL_PROT_PTRC3_NamPlt_swRev (&iedModel_PROT_PTRC3_NamPlt_swRev)
#define IEDMODEL_PROT_PTRC3_Tr (&iedModel_PROT_PTRC3_Tr)
#define IEDMODEL_PROT_PTRC3_Tr_general (&iedModel_PROT_PTRC3_Tr_general)
#define IEDMODEL_PROT_PTRC3_Tr_q (&iedModel_PROT_PTRC3_Tr_q)
#define IEDMODEL_PROT_PTRC3_Tr_t (&iedModel_PROT_PTRC3_Tr_t)
#define IEDMODEL_PROT_PTRC3_Beh (&iedModel_PROT_PTRC3_Beh)
#define IEDMODEL_PROT_PTRC3_Beh_stVal (&iedModel_PROT_PTRC3_Beh_stVal)
#define IEDMODEL_PROT_PTRC3_Beh_q (&iedModel_PROT_PTRC3_Beh_q)
#define IEDMODEL_PROT_PTRC3_Beh_t (&iedModel_PROT_PTRC3_Beh_t)
#define IEDMODEL_PROT_PTRC3_Op (&iedModel_PROT_PTRC3_Op)
#define IEDMODEL_PROT_PTRC3_Op_general (&iedModel_PROT_PTRC3_Op_general)
#define IEDMODEL_PROT_PTRC3_Op_q (&iedModel_PROT_PTRC3_Op_q)
#define IEDMODEL_PROT_PTRC3_Op_t (&iedModel_PROT_PTRC3_Op_t)
#define IEDMODEL_PROT_PTRC3_Health (&iedModel_PROT_PTRC3_Health)
#define IEDMODEL_PROT_PTRC3_Health_stVal (&iedModel_PROT_PTRC3_Health_stVal)
#define IEDMODEL_PROT_PTRC3_Health_q (&iedModel_PROT_PTRC3_Health_q)
#define IEDMODEL_PROT_PTRC3_Health_t (&iedModel_PROT_PTRC3_Health_t)
#define IEDMODEL_PROT_PTRC3_Str (&iedModel_PROT_PTRC3_Str)
#define IEDMODEL_PROT_PTRC3_Str_general (&iedModel_PROT_PTRC3_Str_general)
#define IEDMODEL_PROT_PTRC3_Str_dirGeneral (&iedModel_PROT_PTRC3_Str_dirGeneral)
#define IEDMODEL_PROT_PTRC3_Str_q (&iedModel_PROT_PTRC3_Str_q)
#define IEDMODEL_PROT_PTRC3_Str_t (&iedModel_PROT_PTRC3_Str_t)
#define IEDMODEL_PROT_PTRC3_OpCntRs (&iedModel_PROT_PTRC3_OpCntRs)
#define IEDMODEL_PROT_PTRC3_OpCntRs_stVal (&iedModel_PROT_PTRC3_OpCntRs_stVal)
#define IEDMODEL_PROT_PTRC3_OpCntRs_q (&iedModel_PROT_PTRC3_OpCntRs_q)
#define IEDMODEL_PROT_PTRC3_OpCntRs_t (&iedModel_PROT_PTRC3_OpCntRs_t)
#define IEDMODEL_PROT_PTRC3_OpCntRs_ctlModel (&iedModel_PROT_PTRC3_OpCntRs_ctlModel)
#define IEDMODEL_PROT_PTRC3_Mod (&iedModel_PROT_PTRC3_Mod)
#define IEDMODEL_PROT_PTRC3_Mod_stVal (&iedModel_PROT_PTRC3_Mod_stVal)
#define IEDMODEL_PROT_PTRC3_Mod_q (&iedModel_PROT_PTRC3_Mod_q)
#define IEDMODEL_PROT_PTRC3_Mod_t (&iedModel_PROT_PTRC3_Mod_t)
#define IEDMODEL_PROT_PTRC3_Mod_ctlModel (&iedModel_PROT_PTRC3_Mod_ctlModel)
#define IEDMODEL_PROT_PTRC4 (&iedModel_PROT_PTRC4)
#define IEDMODEL_PROT_PTRC4_NamPlt (&iedModel_PROT_PTRC4_NamPlt)
#define IEDMODEL_PROT_PTRC4_NamPlt_vendor (&iedModel_PROT_PTRC4_NamPlt_vendor)
#define IEDMODEL_PROT_PTRC4_NamPlt_swRev (&iedModel_PROT_PTRC4_NamPlt_swRev)
#define IEDMODEL_PROT_PTRC4_Tr (&iedModel_PROT_PTRC4_Tr)
#define IEDMODEL_PROT_PTRC4_Tr_general (&iedModel_PROT_PTRC4_Tr_general)
#define IEDMODEL_PROT_PTRC4_Tr_q (&iedModel_PROT_PTRC4_Tr_q)
#define IEDMODEL_PROT_PTRC4_Tr_t (&iedModel_PROT_PTRC4_Tr_t)
#define IEDMODEL_PROT_PTRC4_Beh (&iedModel_PROT_PTRC4_Beh)
#define IEDMODEL_PROT_PTRC4_Beh_stVal (&iedModel_PROT_PTRC4_Beh_stVal)
#define IEDMODEL_PROT_PTRC4_Beh_q (&iedModel_PROT_PTRC4_Beh_q)
#define IEDMODEL_PROT_PTRC4_Beh_t (&iedModel_PROT_PTRC4_Beh_t)
#define IEDMODEL_PROT_PTRC4_Op (&iedModel_PROT_PTRC4_Op)
#define IEDMODEL_PROT_PTRC4_Op_general (&iedModel_PROT_PTRC4_Op_general)
#define IEDMODEL_PROT_PTRC4_Op_q (&iedModel_PROT_PTRC4_Op_q)
#define IEDMODEL_PROT_PTRC4_Op_t (&iedModel_PROT_PTRC4_Op_t)
#define IEDMODEL_PROT_PTRC4_Health (&iedModel_PROT_PTRC4_Health)
#define IEDMODEL_PROT_PTRC4_Health_stVal (&iedModel_PROT_PTRC4_Health_stVal)
#define IEDMODEL_PROT_PTRC4_Health_q (&iedModel_PROT_PTRC4_Health_q)
#define IEDMODEL_PROT_PTRC4_Health_t (&iedModel_PROT_PTRC4_Health_t)
#define IEDMODEL_PROT_PTRC4_Str (&iedModel_PROT_PTRC4_Str)
#define IEDMODEL_PROT_PTRC4_Str_general (&iedModel_PROT_PTRC4_Str_general)
#define IEDMODEL_PROT_PTRC4_Str_dirGeneral (&iedModel_PROT_PTRC4_Str_dirGeneral)
#define IEDMODEL_PROT_PTRC4_Str_q (&iedModel_PROT_PTRC4_Str_q)
#define IEDMODEL_PROT_PTRC4_Str_t (&iedModel_PROT_PTRC4_Str_t)
#define IEDMODEL_PROT_PTRC4_OpCntRs (&iedModel_PROT_PTRC4_OpCntRs)
#define IEDMODEL_PROT_PTRC4_OpCntRs_stVal (&iedModel_PROT_PTRC4_OpCntRs_stVal)
#define IEDMODEL_PROT_PTRC4_OpCntRs_q (&iedModel_PROT_PTRC4_OpCntRs_q)
#define IEDMODEL_PROT_PTRC4_OpCntRs_t (&iedModel_PROT_PTRC4_OpCntRs_t)
#define IEDMODEL_PROT_PTRC4_OpCntRs_ctlModel (&iedModel_PROT_PTRC4_OpCntRs_ctlModel)
#define IEDMODEL_PROT_PTRC4_Mod (&iedModel_PROT_PTRC4_Mod)
#define IEDMODEL_PROT_PTRC4_Mod_stVal (&iedModel_PROT_PTRC4_Mod_stVal)
#define IEDMODEL_PROT_PTRC4_Mod_q (&iedModel_PROT_PTRC4_Mod_q)
#define IEDMODEL_PROT_PTRC4_Mod_t (&iedModel_PROT_PTRC4_Mod_t)
#define IEDMODEL_PROT_PTRC4_Mod_ctlModel (&iedModel_PROT_PTRC4_Mod_ctlModel)

#endif /* STATIC_MODEL_H_ */

